<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <authors>Höglandets IT</authors>
    <copyright>Copyright © 2025- Höglandets IT</copyright>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kommunkod/restclone</PackageProjectUrl>
    <Description>Cross-platform tasks for managing remote filesystems</Description>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSource>True</IncludeSource>
    <PackageTags>Frends</PackageTags>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.9.1</Version>
    <Configurations>Release;Debug</Configurations>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Kommunkod.Restclone</PackageId>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/kommunkod/restclone</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="restclone.dll" Pack="true" PackagePath="/">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>