name: Build and Publish Packages

on:
  push:
    branches:
      - main
    tags: ["*.*.*"]

permissions:
  contents: write

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.2
      id: go

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Swagger Docs
      run: |
        go mod tidy
        go tool swag init -g cmd/main.go --output docs --md . --parseDepth 200 --parseDependency

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}