name: Build and Publish Packages
description: |
  Workflow for continuously testing the c-shared build which is used in external projects.

on:
  push:
    branches: ["main"]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.2
      id: go

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run GoReleaser for c-shared
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --snapshot -f .goreleaser-cshared.yaml --skip=announce,publish,validate,ko,sign --fail-fast
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run GoReleaser for specific platform as test
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --snapshot --skip=announce,publish,validate,ko,sign --fail-fast
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
            dist-cshared/*
            dist/*
        name: goreleaser-artifacts
        retention-days: 3